### ISSUE TITLE
Add watcher to project

### ISSUE THREAD

**Issue by kddrake** [Jropp/jason-ropp-js-iobp#15]
## Goal
Keep your server running while your files are watched and reloaded upon update

### When Accomplished
- [x] Running `npm start` from the command line will **also** start watching your files for changes using webpack-dev-server
- [x] Css files will be applied properly
- [x] Saving changes to your HTML files will only require a browser reload to observe

### Notes
_None._

### Don't Start Until Completing

- [x] #26 - webpack-dev-server wraps around webpack. It watches and automatically refreshes the browser on changes.

## Changes

webpack-dev-server wraps around webpack and automatically bundles then serves the files. They don't get ceated into a dist folder, they just get served. 

Starting with the local file creation is good, because then dev-server works well on top of those settings, all you have to do is change the webpack script to webpack-dev-server

**Comment by Jropp** [comment]
@kddrake the second item already seems to be happening. I've never had to restart the server after making changes. I've always hit save and then refreshed the page in the browser. 

Is this because of something inherent in Visual Code Studio or the python server? 
Should I add something like nodemon anyway? 

Also is it alright to add https://www.npmjs.com/package/reload along with nodemon? I am sufficiently lazy that the extra refresh keystrokes are annoying.

**Comment by kddrake** [comment]
Ah, that makes sense now that you mention it. It's not VCS or the server, all your files are just static so there's nothing _too_ update. When you update the file, you update what's served.

Once we get to bundling that'll be a difference story. So you could hold off on this issue until then.

**Comment by Jropp** [comment]
@kddrake does using webpack-dev-server close out this issue?

**Comment by kddrake** [comment]
@Jropp as long as webpack-dev-server watches for changes, yup.

**Comment by Jropp** [comment]
#26 webpack dev server fixes this
